import com.sample.*;
import com.sample.entities.*;
import com.sample.classifications.*;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;


rule "investitor la inceputul carierei"
when
    investitor1 : Investitor(etapaCarierei == Cariera.INCEPUT)
    recomandare : Recomandare(investitor == investitor1)
then
    Plasament plasament1 = new Plasament("ING - Depozit de economii", "depozit la vedere", 0.007);
    PlasamentRecomandat plasamentRecomandat1 = new PlasamentRecomandat(recomandare, plasament1, 0.4);
    recomandare.getPlasamente().add(plasamentRecomandat1);
    
    Plasament plasament2 = new Plasament("ING - Depozit de economii la termen", "depozit la termen", 0.02);
    PlasamentRecomandat plasamentRecomandat2 = new PlasamentRecomandat(recomandare, plasament2, 0.6);
    recomandare.getPlasamente().add(plasamentRecomandat2);    
end